### PR TITLE
Routing rule leasing to welcome/shucks - Closes issue#4

### PR DESCRIPTION
**Pull request by ivelin-dev**

### CODE REVIEW

**Comment by Derek03** [comment]
Ivelin can you merge you conflicts?

**Comment by ivelin-dev** [comment]
I'm trying to figure out how. I had no problems with the previous PR's. I think someone changed the Welcome.php @Derek03

**Comment by Derek03** [comment]
Sounds good @Ivelin1995

**Comment by ivelin-dev** [comment]
@Derek03 I can't figure out what's causing the merge conflict. I've been trying for an hour now. The only lines I want to add are the following:
In routes.php:
`$route['lock/(:any)/(:any)'] = 'welcome/shucks';`

and in Welcome.php:

```
public function shucks()
    {
        // this is the view we want shown
        $this->data['pagebody'] = 'justone';

        // build the list of authors, to pass on to our view
        $source = $this->quotes->get(2);

        $this->data['what'] = $source['what'];
        $this->data['who'] = $source['who'];
        $this->data['mug'] = $source['mug'];


        $this->render();
    }
```

@Derek03 can you try adding them? I have a feeling the lines we are working on are the same.

**Comment by Derek03** [comment]
@Ivelin1995  I'll try it out.

**Comment by Derek03** [comment]
I've fixed it and merged it.

**Comment by ivelin-dev** [comment]
Thanks!

**Pull request closed without merging**
